### API Endpoints, THIS IS ONLY FOR TESTING
### Get Users
GET http://localhost:3000/users/
###Send Users
POST http://localhost:3000/users/register
Content-Type: application/json

{
    "email": "lolitoFdf@hotmail.com",
    "username": "Jesus cree en ti",
    "password": "chupachupsdementa"
}

###LOGIN Users
POST http://localhost:3000/users/login
Content-Type: application/json

{
    "email": "lolitoFdf@hotmail.com",
    "username": "Jesus",
    "password": "chupachupsdementa"    
}

### Update user
PATCH  http://localhost:3000/users/me
Content-Type: application/json

{
    "email": "lolitoFdf@hotmail.com",
    "username": "Jesus",
    "password": "chupachupsdementa"
}
### Delete user
DELETE http://localhost:3000/users/me
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4NWMyNjc3ZTJiMTExMTMxNjJkOWE0ZSIsImlhdCI6MTc1MDkzMDE1OCwiZXhwIjoxNzUwOTMzNzU4fQ.P5waSlv0wzAsUyPGBo7ibUb-QbEaXmOQi2rciRrAkeo

{
    "email": "lolitoFdf@hotmail.com"
}