### API Endpoints
### Get Users
GET http://localhost:3000/users/
###Send Users
POST http://localhost:3000/users/register
Content-Type: application/json

{
    "email": "lolitoFdf@hotmail.com",
    "username": "Jesus cree en ti",
    "password": "chupachupsdementa"
}

###LOGIN Users
POST http://localhost:3000/users/login
Content-Type: application/json

{
    "email": "lolitoFdf@hotmail.com",
    "username": "Jesus cree en ti",
    "password": "chupachupsdementa"    
}