### API Endpoints, THIS IS ONLY FOR TESTING
### Get Users
GET http://localhost:3000/users/
###Send Users
POST http://localhost:3000/users/register
Content-Type: application/json

{
    "email": "mariano@hotmail.com",
    "username": "mariano",
    "password": "123456789"
}

###LOGIN Users
POST http://localhost:3000/users/login
Content-Type: application/json

{
    "email": "mariano@hotmail.com",
    "username": "mariano",
    "password": "123456789"    
}

### Update user
PATCH  http://localhost:3000/users/me
Content-Type: application/json

{
    "email": "lolitoFdf@hotmail.com",
    "username": "Jesus",
    "password": "chupachupsdementa"
}
### Delete user
DELETE http://localhost:3000/users/me
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4NWQxYWNmY2EyMTlhODdjODE0YjA0ZiIsImlhdCI6MTc1MDkzMjIxOCwiZXhwIjoxNzUwOTM1ODE4fQ.U8v6PWp04V1eG4J2-o4obtcGpei7NxQu-4qgsXKf5EY

{
    "email": "lolitoFdf@hotmail.com"
}